//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY DF GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/df_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: require_trailing_commas
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_question_mark
// ignore_for_file: unnecessary_this

part of 'model_js_navigator.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelJsNavigator extends _ModelJsNavigator {
  //
  //
  //

  static const CLASS_NAME = 'ModelJsNavigator';

  @override
  String get $className => CLASS_NAME;

  final String? userAgent;

  //
  //
  //

  const ModelJsNavigator({
    this.userAgent,
  });

  const ModelJsNavigator.c2({
    this.userAgent,
  });

  factory ModelJsNavigator.c3({
    String? userAgent,
  }) {
    return ModelJsNavigator(
      userAgent: userAgent,
    );
  }

  factory ModelJsNavigator.from(
    BaseModel? other,
  ) {
    try {
      return fromOrNull(other)!;
    } catch (e) {
      assert(false, 'ModelJsNavigator.from: $e');
      rethrow;
    }
  }

  @pragma('vm:prefer-inline')
  static ModelJsNavigator? fromOrNull(
    BaseModel? other,
  ) {
    return fromJsonOrNull(other?.toJson())!;
  }

  factory ModelJsNavigator.of(
    ModelJsNavigator other,
  ) {
    try {
      return ofOrNull(other)!;
    } catch (e) {
      assert(false, 'ModelJsNavigator.of: $e');
      rethrow;
    }
  }

  @pragma('vm:prefer-inline')
  static ModelJsNavigator? ofOrNull(
    ModelJsNavigator? other,
  ) {
    return fromJsonOrNull(other?.toJson());
  }

  factory ModelJsNavigator.fromJsonString(
    String source,
  ) {
    try {
      return fromJsonStringOrNull(source)!;
    } catch (e) {
      assert(false, 'ModelJsNavigator.fromJsonString: $e');
      rethrow;
    }
  }

  static ModelJsNavigator? fromJsonStringOrNull(
    String? source,
  ) {
    try {
      if (source!.isNotEmpty) {
        final decoded = letMapOrNull<String, dynamic>(jsonDecode(source));
        return ModelJsNavigator.fromJson(decoded);
      } else {
        return const ModelJsNavigator.c2();
      }
    } catch (_) {
      return null;
    }
  }

  factory ModelJsNavigator.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return fromJsonOrNull(otherData)!;
    } catch (e) {
      assert(false, 'ModelJsNavigator.fromJson: $e');
      rethrow;
    }
  }

  static ModelJsNavigator? fromJsonOrNull(
    Map<String, dynamic>? otherData,
  ) {
    try {
      final userAgent = otherData?['userAgent']?.toString().trim().nullIfEmpty;
      return ModelJsNavigator(
        userAgent: userAgent,
      );
    } catch (e) {
      return null;
    }
  }

  factory ModelJsNavigator.fromUri(
    Uri? uri,
  ) {
    try {
      return fromUriOrNull(uri)!;
    } catch (e) {
      assert(false, 'ModelJsNavigator.fromUri: $e');
      rethrow;
    }
  }

  static ModelJsNavigator? fromUriOrNull(
    Uri? uri,
  ) {
    try {
      if (uri != null && uri.path == CLASS_NAME) {
        return ModelJsNavigator.fromJson(uri.queryParameters);
      } else {
        return const ModelJsNavigator.c2();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    bool includeNulls = false,
  }) {
    try {
      final userAgent0 = userAgent?.trim().nullIfEmpty;
      final withNulls = {
        'userAgent': userAgent0,
      };
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, 'ModelJsNavigator.toJson: $e');
      rethrow;
    }
  }

  //
  //
  //

  @override
  ModelJsNavigator mergeWith(
    BaseModel? other, {
    bool deepMerge = false,
  }) {
    final a = toJson();
    final b = other?.toJson() ?? {};
    final data = (deepMerge ? mergeDataDeep(a, b) : {...a, ...b}) as Map;
    return ModelJsNavigator.fromJson(data.cast());
  }

  //
  //
  //

  ModelJsNavigator copyWith({
    String? userAgent,
  }) {
    return ModelJsNavigator.c2(
      userAgent: userAgent ?? this.userAgent,
    );
  }

  //
  //
  //

  ModelJsNavigator copyWithout({
    bool userAgent = true,
  }) {
    return ModelJsNavigator.c2(
      userAgent: userAgent ? this.userAgent : null,
    );
  }

  //
  //
  //

  // userAgent.
  @pragma('vm:prefer-inline')
  String? get userAgentField => this.userAgent;
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

abstract final class ModelJsNavigatorFieldNames {
  static const userAgent = 'userAgent';
}
